### ISSUE TITLE
Topics migration_lookup in newsroom_item migration

### ISSUE THREAD

**Issue by StefanieVermandele** [LOBsTerr/newsroom_connector#4]
Working with Drupal 9.3, a fresh install.

I have the newsroom_connector module and the newsroom_connector_item, newsroom_connector_media, newsroom_connector_topic and newsroom_connector_type submodules enabled.

The newsroom_topic and newsroom_item (and other dependent) migrations have run successfully, but the migration_lookup for topics doesn't produce any results. 
The selected topics are present in the website. I can see the topics in the feed for my newsroom item and I can match them to the items that were migrated by the newsroom_topic migration.
But the topics are not transferred into the field_newsroom_topics field in my content item in Drupal.

**Comment by LOBsTerr** [comment]
Just installed fresh instance, imported topics with your universe for me everything works as expected.
Do you see any errors in the log ?

**Comment by StefanieVermandele** [comment]
Hi Nikolay,
Thank you for your feedback!
The problem is not with the topic migration itself. It is with the field_newsroom_topics on the newsroom_item content type. No topics are filled in there after running the newsroom_item migration, despite the newsroom_topic migration running successfully, adding the topics in the Newsroom itself and seeing them in the feed for the item.
![Screenshot 2022-12-12 at 16 18 37](https://user-images.githubusercontent.com/120397819/209348678-b92ccc3f-aa28-4143-bffd-59d413a3b2df.png)


Could it be that the problem lies in the newsroom_item migration?
I see that the selector for the topics field is:
`selector: 'category[@domain="Subchapter"]/@infsonewsroom:TopicId'`
But 'Subchapter' seems to be wrong. If I replace 'Subchapter' by our type 'Theme', the topics are imported correctly into the newsroom item.

(Just for clarity: no primary topic or highlighted topic is added to the newsroom item either, unless I replace 'Subchapter' by our type 'Theme' in the corresponding selectors.)

**Comment by LOBsTerr** [comment]
Ok, I see

**Comment by LOBsTerr** [comment]
Fixed in a new release 1.3.2
